on: push

jobs:
  ubuntu-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run steps
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo $GITHUB_TOKEN TTT