on: push

jobs:
  mac-os-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        shell: bash
        run: |
          echo "export GITHUB_TOKEN=${{ secrets.TOKEN }}" >> .env
      - name: Run steps
        shell: bash
        run: |


          echo "Installing Scala"
          brew install coursier/formulas/coursier -f && cs setup -y
          echo "Scala Installed"

          source ~/.profile

          echo "Installing Giter"
          cs install giter8
          echo "Gitter Installed"

          scripts/hydra install

          scripts/hydra build

          scripts/hydra start_genesis

          scripts/hydra stop

          scripts/hydra destroy